// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKosSME6X9SNpxOTo1S4qF0u1yDEMlco',
    appId: '1:622334209327:web:e893fe0cdb7cfea60285da',
    messagingSenderId: '622334209327',
    projectId: 'happyhappyhappy-3ae81',
    authDomain: 'happyhappyhappy-3ae81.firebaseapp.com',
    databaseURL: 'https://happyhappyhappy-3ae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happyhappyhappy-3ae81.appspot.com',
    measurementId: 'G-2478RHMPTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6LJjH9FYwlo33l0lde3ZuU1bbBGAOrRo',
    appId: '1:622334209327:android:2deb78c41211ee100285da',
    messagingSenderId: '622334209327',
    projectId: 'happyhappyhappy-3ae81',
    databaseURL: 'https://happyhappyhappy-3ae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happyhappyhappy-3ae81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9oqfKNnfu1W2pKcucjycSTjygb706CA',
    appId: '1:622334209327:ios:f90f039381f057570285da',
    messagingSenderId: '622334209327',
    projectId: 'happyhappyhappy-3ae81',
    databaseURL: 'https://happyhappyhappy-3ae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happyhappyhappy-3ae81.appspot.com',
    iosBundleId: 'com.example.happyhappyhappy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu9oqfKNnfu1W2pKcucjycSTjygb706CA',
    appId: '1:622334209327:ios:56a6ba74d62990450285da',
    messagingSenderId: '622334209327',
    projectId: 'happyhappyhappy-3ae81',
    databaseURL: 'https://happyhappyhappy-3ae81-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happyhappyhappy-3ae81.appspot.com',
    iosBundleId: 'com.example.happyhappyhappy.RunnerTests',
  );
}
