// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfndnlYOqGkADHxV0BV_kX3mC3BTboWYU',
    appId: '1:99875069672:web:89ad7296b3a8ee5629735d',
    messagingSenderId: '99875069672',
    projectId: 'happyhappyhappy2-e2ceb',
    authDomain: 'happyhappyhappy2-e2ceb.firebaseapp.com',
    storageBucket: 'happyhappyhappy2-e2ceb.appspot.com',
    measurementId: 'G-Q8BYCHHNZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCot9_jZo7V4ayF6_eUWnk1ZWFwLaPDW-I',
    appId: '1:99875069672:android:a040e5cb453a29e329735d',
    messagingSenderId: '99875069672',
    projectId: 'happyhappyhappy2-e2ceb',
    storageBucket: 'happyhappyhappy2-e2ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN1iiw7shd33aj5X01bmb-t49N5jb5D0g',
    appId: '1:99875069672:ios:7ccbff403376746529735d',
    messagingSenderId: '99875069672',
    projectId: 'happyhappyhappy2-e2ceb',
    storageBucket: 'happyhappyhappy2-e2ceb.appspot.com',
    iosBundleId: 'com.example.happyhappyhappy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN1iiw7shd33aj5X01bmb-t49N5jb5D0g',
    appId: '1:99875069672:ios:56370a2878cf150529735d',
    messagingSenderId: '99875069672',
    projectId: 'happyhappyhappy2-e2ceb',
    storageBucket: 'happyhappyhappy2-e2ceb.appspot.com',
    iosBundleId: 'com.example.happyhappyhappy.RunnerTests',
  );
}
